### ISSUE TITLE
Update busybox image to a more standard quay/docker image

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ocm-ramen-samples#22]
Current busybox image in use is [here](https://github.com/RamenDR/ocm-ramen-samples/blob/b995865a771ae7a9c92e400892d15aa2c664f00f/busybox-odr-metro/busybox-pod.yaml#L11).

This is for the pod definitions in `busybox-ord*` directories, and needs to change to a more standard image from quay or docker.

**Comment by nirs** [comment]
In ramen test example we use now docker.io/library/busybox:stable

This also avoid the need to specify `imagePullPolicy: IfNotPresent`. It is needed because we
used `:latest`.
